--- #YAML:1.0
name:                Acme-Anything
version:             0.03
abstract:            Anything, even imaginary modules are loadable
license:             ~
author:              
    - Josh ben Jore <jjore@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
